### ISSUE TITLE
Test fail to run - xpath issue in wps.xml ctl

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wps10#1]
Exception in thread "TEAM Engine" java.lang.Exception: Fatal Error: XPath syntax error at char 70 on line 123 in {...ogc.schema.root, $ows.versi...}:
    Cannot find a matching 2-argument function named {https://cite.opengeospatial.org/wps-1.0.0/src/ctl/functions.xml}exceptionReportSchemaPath(); SystemID: file:/Users/lbermudez/teamengine/TE_BASE/work/_Users_lbermudez_teamengine_TE_BASE_scripts_wps_1.0.0_ctl_wps.xml/wps$Main.test; Line#: 123; Column#: -1
Failed to compile stylesheet. 1 error detected.
	at com.occamlab.te.Engine.loadExecutable(Engine.java:189)
	at com.occamlab.te.TECore.executeTemplate(TECore.java:498)
	at com.occamlab.te.TECore.executeTest(TECore.java:660)
	at com.occamlab.te.TECore.execute_test(TECore.java:347)
	at com.occamlab.te.TECore.execute_suite(TECore.java:390)
	at com.occamlab.te.TECore.execute(TECore.java:252)
	at com.occamlab.te.Test.main(Test.java:354)
Caused by: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
	at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)
	at net.sf.saxon.PreparedStylesheet.compile(PreparedStylesheet.java:79)
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:146)
	at com.occamlab.te.Engine.loadExecutable(Engine.java:181)
	... 6 more

**Comment by bermud** [comment]
This issue is not happing anymore.  Tested with TE 4.1 and fixing the structure of the test in revision 0.3
