### ISSUE TITLE
Failed running via command line

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wps10#8]
When testing with 4.8.1 and 0.6 version, I get this error:

```
Luiss-MacBook-Pro-2:unix lbermudez$ ./test.sh -source=wps/1.0.0/ctl/wps.xml
Testing suite was:suite in Test Mode with defaultResult of Pass ...
******************************************************************************************************************************
   Testing was:Main type Mandatory in Test Mode with defaultResult Pass (s0003)...
      Assertion: The IUT satisfies all applicable assertions.
Exception in thread "TEAM Engine" java.lang.Exception: Fatal Error: Path syntax error at char 70 on line 136 in {...ogc.schema.root, $ows.versi...}:
    Cannot find a matching 2-argument function named {https://cite.opengeospatial.org/wps-1.0.0/src/ctl/functions.xml}exceptionReportSchemaPath(); SystemID: file:/Users/lbermudez/te-build/catalina_base/TE_BASE/work/_Users_lbermudez_te-build_catalina_base_TE_BASE_scripts_wps_1.0.0_ctl_wps.xml/wps$Main.test; Line#: 136; Column#: -1
Failed to compile stylesheet. 1 error detected.
    at com.occamlab.te.Engine.loadExecutable(Engine.java:190)
    at com.occamlab.te.TECore.executeTemplate(TECore.java:557)
    at com.occamlab.te.TECore.executeTest(TECore.java:787)
    at com.occamlab.te.TECore.execute_test(TECore.java:395)
    at com.occamlab.te.TECore.execute_suite(TECore.java:443)
    at com.occamlab.te.TECore.execute(TECore.java:300)
    at com.occamlab.te.Test.execute(Test.java:318)
    at com.occamlab.te.Test.main(Test.java:91)
Caused by: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
    at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)
    at net.sf.saxon.PreparedStylesheet.compile(PreparedStylesheet.java:79)
    at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:146)
    at com.occamlab.te.Engine.loadExecutable(Engine.java:181)
    ... 7 more

```

**Comment by bermud** [comment]
@keshav-nangare, please verify that this is still an issue, with the latest TE and 0.6

**Comment by keshav-nangare** [comment]
Is there any other capability-URL available?

Existing capability URL is not working: http://host1.geolabs.fr:5001/cgi-bin/zoo_loader.cgi


Fixed with this commit: 7daa1d840ad8bd301b620c6218d3876acd98b906

**Comment by lgoltz** [comment]
Service for testing is missing.

**Comment by ghobona** [comment]
Overtaken by events.
